=== magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/DataGenerator/etc/dataProfileSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 /**
  * Copyright Â© Magento, Inc. All rights reserved.
  * See COPYING.txt for license details.
  */
-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="entities">
        <xs:annotation>
            <xs:documentation>
                The root element for configuration data.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element type="entityType" name="entity" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration array containing all Entity elements.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="entityType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="data" type="dataType" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Element containing Data/Value pair.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="var" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="dataType">
                            <xs:attribute name="entityType" type="xs:string"/>
                            <xs:attribute name="entityKey" type="xs:string"/>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="requiredEntity" type="requiredEntityType" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Element containing required entity to this parent entity.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="array" type="arrayType" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                       Element that contains a reference to non singular data/values.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
        <xs:attribute type="xs:string" name="name">
            <xs:annotation>
                <xs:documentation>
                    Name of the Entity.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" name="type">
            <xs:annotation>
                <xs:documentation>
                    Node containing the exact name of Entity type. Used later to find specific Persistence Layer Model
                    class.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" name="extends">
            <xs:annotation>
                <xs:documentation>
                    Name of the entity that is extended.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" name="filename"/>
    </xs:complexType>

    <xs:complexType name="dataType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="key" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            Key attribute of data/value pair.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute type="uniquenessEnumType" name="unique" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            Add suite or test wide unique sequence as "prefix" or "suffix" to the data value if specified.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="arrayType">
        <xs:sequence>
            <xs:element name="item" type="xs:string" maxOccurs="unbounded" minOccurs="0">
            <xs:annotation>
                <xs:documentation>
                    Individual piece of data to be passed in as part of the parrent array type.
                </xs:documentation>
            </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="key" use="required"/>
    </xs:complexType>

    <xs:complexType name="requiredEntityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="type" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            Type attribute of required entity.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="uniquenessEnumType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="prefix" />
            <xs:enumeration value="suffix" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== magento/magento2-functional-testing-framework/dev/tests/verification/TestModule/Data/ParameterArrayData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright 2017 Adobe
 * All Rights Reserved.
 */
-->

<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:mftf:DataGenerator/etc/dataProfileSchema.xsd">
    <entity name="simpleParamData" type="data">
        <data key="name">name</data>
        <data key="uniqueNamePre" unique="prefix">prename</data>
        <data key="uniqueNamePost" unique="suffix">postname</data>
    </entity>
    <entity name="testEntity" type="sample">
        <data key="sampleField">value1</data>
        <requiredEntity type="test">originalValue</requiredEntity>
        <requiredEntity type="test3">originalValue3</requiredEntity>
    </entity>
</entities>

=== magento/magento2-functional-testing-framework/dev/tests/verification/TestModule/Data/ReplacementData.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 /**
  * Copyright Â© Magento, Inc. All rights reserved.
  * See COPYING.txt for license details.
  */
-->

<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../src/Magento/FunctionalTestingFramework/DataGenerator/etc/dataProfileSchema.xsd">
    <entity name="simpleData" type="simpleData">
        <data key="firstname">John</data>
        <data key="lastname">Doe</data>
        <data key="middlename">Tiberius</data>
    </entity>
    <entity name="uniqueData" type="simpleData">
        <data key="firstname" unique="prefix">John</data>
        <data key="lastname" unique="suffix">Doe</data>
    </entity>
</entities>
